spring:
  kafka:
    properties:
      bootstrap-servers: localhost:9092

    consumer:
      properties:
        group-id: find-the-dog-group
    producer:
      properties:
        group-id: find-the-dog-group
